# Generated by Django 4.2.6 on 2023-11-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('opcoes', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
    ]
